[features]
seeds = false
skip-lint = false

[programs.localnet]
strategic_duel = "4afPz2WpaejNd2TrnneC4ybC7Us86WBqkJyQa7pnkkdr"

[programs.devnet]
strategic_duel = "4afPz2WpaejNd2TrnneC4ybC7Us86WBqkJyQa7pnkkdr"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[[test.genesis]]
address = "MagicBLockxxx1111111111111111111111111111"
program = "./target/deploy/magicblock_bolt.so"

[[test.genesis]]
address = "SBV2111111111111111111111111111111111111111"
program = "./target/deploy/switchboard_v2.so"