[package]
name = "shared"
version = "0.1.0"
description = "SOL Duel Shared Libraries"
edition = "2021"

[dependencies]
anchor-lang = { workspace = true }
solana-program = { workspace = true }

[dev-dependencies]
tokio = { workspace = true }