[toolchain]
anchor_version = "0.30.0"

[features]
resolution = true
skip-lint = false

[programs.localnet]
pvp_gambling = "7xKXtg2CW87d97TXJSDpbD5jBkheTqA83TZRuJosgHfC"

[programs.devnet]
pvp_gambling = "7xKXtg2CW87d97TXJSDpbD5jBkheTqA83TZRuJosgHfC"

[programs.mainnet-beta]
pvp_gambling = "7xKXtg2CW87d97TXJSDpbD5jBkheTqA83TZRuJosgHfC"

[registry]
url = "https://api.anchor-platform.com"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[test]
startup_wait = 5000
shutdown_wait = 2000
upgradeable = false

[[test.validator.account]]
address = "So11111111111111111111111111111111111111112"
filename = "test-fixtures/spl-token.so"

[[test.validator.clone]]
address = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s"